name: "branch"

on:
  push:
    branches:
      - '*/*'
      - '*'
      - '!master'
    tags:
      - '!refs/tags/*'

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      DOTNET_NOLOGO: true
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
      - name: Build
        run: dotnet build -c Release
      - name: Tests
        run: dotnet test -c Release --no-build
