name: "Build and Publish to GitHub"

on:
  push:
    branches:
      - master
    tags:
      - '!refs/tags/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: dotnet build -c Release
    - name: Tests
      run: dotnet test -c Release --no-build
    - name: Pack
      run: dotnet pack src -c Release --no-build --version-suffix build-$(date +%Y%m%d%H%M) -o artifacts/
    - name: Publish to GitHub
      run: dotnet nuget push "artifacts/*.nupkg" --api-key ${{ secrets.GH_DEPLOY_KEY }} --skip-duplicate --no-symbols true --source "github"
