name: "Build and Publish to NuGet"

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Build
      run: dotnet build -c Release
    - name: Tests
      run: dotnet test -c Release --no-build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Pack
      run: dotnet pack src -c Release --include-symbols --include-source -o artifacts/
    - name: Publish to MyGet
      run: dotnet nuget push artifacts/*.nupkg --api-key ${{ secrets.NUGET_DEPLOY_KEY }} --source https://www.nuget.org/api/v2/package
    - name: Publish Symbols to MyGet
      run: dotnet nuget push artifacts/*.symbols.nupkg --api-key ${{ secrets.NUGET_DEPLOY_KEY }} --source https://nuget.smbsrc.net/
